/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Créer un compte
         * @description Crée un user, hash le password (bcrypt cost 12), pose le cookie refresh et renvoie un access token. Password fort exigé.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        pseudo: string;
                        /** Format: email */
                        email: string;
                        /** @description ≥ 8 caractères, au moins une majuscule, une minuscule, un chiffre et un caractère spécial. */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Compte créé */
                201: {
                    headers: {
                        /** @description refresh (httpOnly, Secure, SameSite=Strict, Path=/auth, 7j) */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSuccess"];
                    };
                };
                /** @description Validation échouée */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
                /** @description Pseudo ou email déjà pris */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Se connecter
         * @description Vérifie email + password. Si 2FA activée, renvoie `{ requires2FA, tempToken }` SANS cookie ni accessToken. Sinon flux normal. Comptes OAuth-only (sans password) renvoient 401.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Connexion réussie OU 2FA requise */
                200: {
                    headers: {
                        /** @description refresh (seulement si 2FA non activée) */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSuccess"] | components["schemas"]["Requires2FA"];
                    };
                };
                /** @description Validation échouée */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
                /** @description Identifiants invalides */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil du user connecté */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renouveler l'access token
         * @description Lit le cookie refresh et émet un nouvel access token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nouvel access token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken: string;
                        };
                    };
                };
                /** @description Refresh token absent ou invalide */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Se déconnecter
         * @description Efface le cookie refresh.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Démarrer le flow Google
         * @description Redirige (302) vers l'écran de consentement Google. Route fournie par @fastify/oauth2 (startRedirectPath). Scopes : profile, email.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirection vers Google */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback Google
         * @description Échange le code, récupère le profil Google, applique le linking 3-cas (A: déjà lié / B: lié par email / C: nouveau compte), pose le cookie refresh et renvoie un access token.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Code d'autorisation fourni par Google */
                    code?: string;
                    state?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connexion OAuth réussie */
                200: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSuccess"];
                    };
                };
                /** @description Échec du login OAuth */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initialiser la 2FA
         * @description Génère un secret base32 + QR code (data URL). Stocke le secret.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Secret + QR code */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Secret base32 (à saisir manuellement si besoin) */
                            secret: string;
                            /** @description Image PNG en data URL pour l'app TOTP */
                            qrCodeDataUrl: string;
                        };
                    };
                };
                /** @description 2FA déjà activée */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activer la 2FA
         * @description Vérifie le 1er code TOTP et passe totp_enabled à true.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 123456 */
                        code: string;
                    };
                };
            };
            responses: {
                /** @description 2FA activée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                /** @description Code invalide, 2FA non configurée ou déjà activée */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"] | components["schemas"]["ValidationError"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Désactiver la 2FA
         * @description Exige un code TOTP valide, puis reset secret + flag.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                    };
                };
            };
            responses: {
                /** @description 2FA désactivée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                /** @description Code invalide ou 2FA non activée */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"] | components["schemas"]["ValidationError"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vérifier le code 2FA au login
         * @description Consomme le tempToken renvoyé par /auth/login, vérifie le code TOTP, puis émet un vrai access token + cookie refresh. Pas d'auth Bearer.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        tempToken: string;
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Connexion finalisée */
                200: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSuccess"];
                    };
                };
                /** @description Code invalide, 2FA non activée ou validation échouée */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"] | components["schemas"]["ValidationError"];
                    };
                };
                /** @description tempToken invalide/expiré ou mauvais type */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mon profil */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Supprimer mon compte
         * @description Suppression définitive. Exige `password` si l'user en a un (sinon ignoré pour les comptes OAuth-only) et `totpCode` si la 2FA est activée. Supprime en cascade friendships, messages, blocks. L'avatar MinIO est aussi retiré (non-bloquant). Le cookie refresh est nettoyé.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Requis si user a un password_hash. */
                        password?: string;
                        /** @description Requis si totp_enabled. */
                        totpCode?: string;
                    };
                };
            };
            responses: {
                /** @description Compte supprimé */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                /** @description Validation échouée (champ requis manquant) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"] | components["schemas"]["ValidationError"];
                    };
                };
                /** @description Password ou code TOTP invalide, ou token absent */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description User introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Modifier mon profil
         * @description Mise à jour partielle de displayName et/ou bio (au moins un champ).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        displayName?: string;
                        bio?: string;
                    };
                };
            };
            responses: {
                /** @description Profil mis à jour */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Aucun champ fourni ou validation échouée */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"] | components["schemas"]["ValidationError"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        trace?: never;
    };
    "/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Uploader un avatar
         * @description Upload multipart (limite 2 MB). MIME autorisés : image/jpeg, image/png, image/webp. Stocke dans MinIO et met à jour avatar_url.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Avatar mis à jour */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Pas multipart, aucun fichier ou type non supporté */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Fichier trop volumineux (> 2 MB) */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/external-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste mes comptes externes liés
         * @description Renvoie les liaisons in-game de l'user authentifié (0 à 4, une par provider). Liste vide si aucune liaison — pas une erreur (jamais 404).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des comptes liés */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            externalAccounts: components["schemas"]["ExternalAccount"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Lier un compte externe
         * @description Lie un compte in-game à l'user (MVP manuel → `verified = false`). Un seul compte par provider (contrainte UNIQUE(user_id, provider)).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        provider: "riot" | "steam" | "epic" | "chess_com";
                        /** @example Faker#KR1 */
                        externalId: string;
                    };
                };
            };
            responses: {
                /** @description Liaison créée */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            externalAccount: components["schemas"]["ExternalAccount"];
                        };
                    };
                };
                /** @description Body invalide (provider hors enum, externalId vide) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Provider déjà lié pour cet user (SQLSTATE 23505) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/external-accounts/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Délier un compte externe
         * @description Retire la liaison de ce provider pour l'user. Idempotent (200 même si aucune liaison existante).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "riot" | "steam" | "epic" | "chess_com";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liaison retirée (ou aucune existante) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                /** @description Provider invalide (hors enum) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{pseudo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil public d'un user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pseudo: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: components["schemas"]["PublicUser"];
                        };
                    };
                };
                /** @description Profil introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste de mes amis */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            friends?: (components["schemas"]["FriendSummary"] & {
                                /** Format: date-time */
                                since?: string;
                            })[];
                        };
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Envoyer une demande d'ami
         * @description Logique 4-cas : pas de relation → pending (201) ; demande inverse existante → auto-accept (200) ; même sens pending → 400 ; déjà amis → 400.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        addresseeId: string;
                    };
                };
            };
            responses: {
                /** @description Demande inverse auto-acceptée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            friendship?: components["schemas"]["Friendship"];
                        };
                    };
                };
                /** @description Demande créée (pending) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            friendship?: components["schemas"]["Friendship"];
                        };
                    };
                };
                /** @description Soi-même, déjà demandé ou déjà amis */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"] | components["schemas"]["ValidationError"];
                    };
                };
                /** @description User cible introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demandes d'amis reçues (pending) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            requests?: {
                                /** Format: uuid */
                                id?: string;
                                /** Format: date-time */
                                sentAt?: string;
                                from?: components["schemas"]["FriendSummary"];
                            }[];
                        };
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accepter une demande
         * @description Seul l'addressee peut accepter.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Demande acceptée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            friendship?: components["schemas"]["Friendship"];
                        };
                    };
                };
                /** @description Déjà amis (status non pending) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Non autorisé (pas l'addressee) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Amitié introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refuser une demande
         * @description Seul l'addressee peut refuser. La ligne est supprimée.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Demande refusée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                /** @description Status non pending */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Non autorisé */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Amitié introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Supprimer un ami
         * @description Unfriend d'une amitié acceptée. Les deux parties (requester ou addressee) peuvent supprimer.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Amitié supprimée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                /** @description Pas d'amitié active à supprimer */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Non autorisé */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Amitié introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{friendId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historique de conversation
         * @description Renvoie les 100 derniers messages échangés avec un ami (ordre chronologique). Réservé aux amitiés acceptées.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    friendId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            messages?: components["schemas"]["Message"][];
                        };
                    };
                };
                /** @description Pas amis */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description User introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des users que j'ai bloqués */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des blocages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            blocks: components["schemas"]["BlockEntry"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bloquer un user
         * @description Bloque l'user et rompt toute amitié existante entre les deux (DELETE friendship dans les deux sens). Pas idempotent : un 2e appel renvoie 400 'already blocked'.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Blocage effectué */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                /** @description Auto-blocage tenté ou déjà bloqué (SQLSTATE 23505) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description User cible introuvable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        /**
         * Débloquer un user
         * @description Retire la ligne `blocks` de moi vers cet user. Idempotent (200 même si pas bloqué).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Déblocage effectué (ou aucun blocage existant) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste les jeux supportés
         * @description Renvoie tous les jeux avec `is_active = true`, triés par nom.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des jeux actifs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            games: components["schemas"]["Game"][];
                        };
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Détails d'un jeu
         * @description Lookup par slug (`lol`, `cs2`, `val`, `rl`, `chess`).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Le jeu demandé */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            game: components["schemas"]["Game"];
                        };
                    };
                };
                /** @description Jeu inconnu ou inactif */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ladders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liste les ladders
         * @description Renvoie tous les ladders triés par nom. Filtre optionnel par `gameId` (slug du jeu). Un `gameId` inconnu renvoie une liste vide (pas d'erreur).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filtre les ladders pour un jeu donné. */
                    gameId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des ladders */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ladders: components["schemas"]["Ladder"][];
                        };
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ladders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Détails d'un ladder (avec son jeu joint)
         * @description Lookup par uuid du ladder. Renvoie le ladder + le jeu parent (JOIN pour éviter au frontend un 2e appel sur `GET /games/{id}`).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Le ladder demandé et son jeu parent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ladder: components["schemas"]["Ladder"];
                            game: components["schemas"]["Game"];
                        };
                    };
                };
                /** @description Ladder inconnu */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ladders/{id}/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Classement (leaderboard) d'un ladder
         * @description Renvoie le classement du ladder, trié par ELO décroissant. Chaque entrée porte un `competitor` qui est soit un joueur (`type: user`), soit une équipe (`type: team`) selon le ladder. Un ladder existant sans classement renvoie une liste vide (pas d'erreur).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Classement trié par ELO décroissant (peut être vide) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            rankings: {
                                /** @example 1 */
                                rank: number;
                                /** @example 1580 */
                                elo: number;
                                wins: number;
                                losses: number;
                                competitor: {
                                    /** @enum {string} */
                                    type: "user";
                                    pseudo: string;
                                    displayName?: string | null;
                                    avatarUrl?: string | null;
                                } | {
                                    /** @enum {string} */
                                    type: "team";
                                    name: string;
                                    logoUrl?: string | null;
                                };
                            }[];
                        };
                    };
                };
                /** @description Ladder inconnu */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mes équipes
         * @description Toutes mes teams, tous jeux et ladders confondus (une par ladder). Liste vide si aucune.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mes teams */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            teams: components["schemas"]["TeamListItem"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Créer une équipe
         * @description Crée une team sur un ladder d'équipe (2v2+). Le créateur devient capitaine ET premier membre (transaction). Refusé sur un ladder 1v1 (solo). Roster plafonné à 10 (enforcé au fil des ajouts).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        ladderId: string;
                        /** @example Bisounours */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Team créée (capitaine ajouté comme membre) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            team: components["schemas"]["Team"];
                        };
                    };
                };
                /** @description Body invalide (ValidationError) ou ladder 1v1 (Error) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"] | components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Ladder inconnu */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Nom déjà pris sur ce ladder, ou déjà dans une team sur ce ladder (23505) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Détail d'une équipe
         * @description Team + ladder aplati + liste des membres (le capitaine y figure avec isCaptain=true).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Détail de la team */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            team: components["schemas"]["TeamDetail"];
                            members: components["schemas"]["TeamMember"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Team inconnue */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Dissoudre une équipe
         * @description Supprime la team (capitaine only). Les membres partent en cascade DB.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Team dissoute (cascade sur les membres) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Seul le capitaine peut dissoudre */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Team inconnue */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ajouter un membre
         * @description Ajoute un membre (capitaine only). Gardes : roster < 10, user existant, pas déjà membre, pas déjà dans une autre team du même ladder.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        userId: string;
                    };
                };
            };
            responses: {
                /** @description Membre ajouté */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                /** @description Body invalide */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Seul le capitaine peut ajouter */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Team ou user inconnu */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Team pleine (10), déjà membre, ou déjà dans une team sur ce ladder */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Retirer un membre (kick ou quit)
         * @description Retire un membre : autorisé au capitaine (kick) ou au membre lui-même (quit). Le capitaine ne peut pas se retirer (400 → dissoudre). Idempotent.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Membre retiré (idempotent) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                /** @description Le capitaine ne peut pas se retirer (dissoudre plutôt) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Ni capitaine, ni le membre lui-même */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Team inconnue */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les slots ouverts d'un ladder (anonyme)
         * @description Slots pending d'un ladder. Team créatrice ET maps masquées (anonymat) ; mes propres slots exclus. Ne renvoie que id / format / jeu / heure.
         */
        get: {
            parameters: {
                query: {
                    ladderId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Slots ouverts (anonymes) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            slots: {
                                /** Format: uuid */
                                id?: string;
                                /** @example 2v2 */
                                format?: string;
                                /** @example val */
                                gameId?: string;
                                /** Format: date-time */
                                scheduledAt?: string;
                            }[];
                        };
                    };
                };
                /** @description Query invalide (ladderId manquant ou non-uuid) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Ladder inconnu */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ladder not found */
                            error?: string;
                        };
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Créer un slot de match (team ou solo 1v1)
         * @description Ouvre un slot (match en attente d'adversaire). Deux modes selon le format du ladder : • **2v2+** : un **capitaine** engage sa team avec une **lineup** (team déduite du ladder). • **1v1** : le **créateur** s'engage **seul** (lineup ignorée, side sans team). Maps BO3 tirées à la création (3 distinctes pour val/cs2 ; [] sinon). Gardes §5.1 (compte externe lié) et §5.2 (slot ouvert unique + lockout temporel), appliquées à la team (2v2+) ou au joueur (1v1).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        ladderId: string;
                        /** Format: date-time */
                        scheduledAt: string;
                        /** @description **Requise en 2v2+** : exactement format_size joueurs (2 / 3 / 5), tous membres de la team, tous avec un compte lié pour le provider du jeu, sans doublon. **Ignorée en 1v1** (le participant = le créateur). */
                        lineup?: string[];
                    };
                };
            };
            responses: {
                /** @description Slot créé (side 0 = ma team, maps tirées) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            match: {
                                /** Format: uuid */
                                id?: string;
                                /** Format: uuid */
                                ladderId?: string;
                                /** @example pending */
                                status?: string;
                                /**
                                 * @example [
                                 *       "Breeze",
                                 *       "Split",
                                 *       "Summit"
                                 *     ]
                                 */
                                maps?: string[];
                                /** Format: date-time */
                                scheduledAt?: string;
                                /** Format: date-time */
                                createdAt?: string;
                            };
                        };
                    };
                };
                /** @description Body invalide (ValidationError) ; scheduledAt dans le passé ; en 2v2+ : lineup manquante/mauvaise taille, pas de team sur ce ladder, joueur hors team ; §5.1 compte non lié (team ou solo) (Error). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"] | components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Seul le capitaine peut créer un match */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Ladder ou jeu inconnu */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description §5.2 — la team a déjà un slot ouvert (pending), ou est en lockout (started_at + lockout_minutes non écoulé). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Détail d'un match (participants only)
         * @description Détail brut : sides (avec teamId), participants et maps. Réservé aux participants — **membre d'une team engagée** (2v2+) **OU joueur du match** (1v1). 403 sinon — préserve l'anonymat des slots ouverts.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Détail du match */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            match: {
                                /** Format: uuid */
                                id?: string;
                                /** Format: uuid */
                                ladderId?: string;
                                status?: string;
                                /** Format: date-time */
                                scheduledAt?: string | null;
                                maps?: string[];
                                /** Format: date-time */
                                createdAt?: string;
                            };
                            sides: {
                                /** @example 0 */
                                sideIndex?: number;
                                /** Format: uuid */
                                teamId?: string | null;
                                participants?: string[];
                            }[];
                        };
                    };
                };
                /** @description Param :id non-uuid (ValidationError) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Non-participant du match */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Match inconnu */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description pong */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example Unauthorized */
            error: string;
        };
        /** @description Erreur de validation Zod (issues brutes). */
        ValidationError: {
            errors: {
                /** @example too_small */
                code?: string;
                path?: string[];
                /** @example au moins 8 caractères */
                message?: string;
            }[];
        };
        Ok: {
            /** @example true */
            ok: boolean;
        };
        /** @description Profil complet du user authentifié (sans passwordHash ni totpSecret). */
        User: {
            /** Format: uuid */
            id: string;
            pseudo: string;
            /** Format: email */
            email: string;
            displayName?: string | null;
            bio?: string | null;
            avatarUrl?: string | null;
            /** @example google */
            oauthProvider?: string | null;
            oauthId?: string | null;
            totpEnabled: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Profil public (GET /users/{pseudo}) — email, updatedAt, totpEnabled et secrets retirés. */
        PublicUser: {
            /** Format: uuid */
            id: string;
            pseudo: string;
            displayName?: string | null;
            bio?: string | null;
            avatarUrl?: string | null;
            oauthProvider?: string | null;
            oauthId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        FriendSummary: {
            /** Format: uuid */
            id?: string;
            pseudo?: string;
            displayName?: string | null;
            avatarUrl?: string | null;
        };
        Friendship: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            requesterId?: string;
            /** Format: uuid */
            addresseeId?: string;
            /** @enum {string} */
            status?: "pending" | "accepted";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Message: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            senderId?: string;
            /** Format: uuid */
            receiverId?: string;
            content?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        AuthSuccess: {
            accessToken: string;
            user: components["schemas"]["User"];
        };
        Requires2FA: {
            /** @example true */
            requires2FA: boolean;
            /** @description Token temporaire (TTL 5 min) à présenter à POST /auth/2fa/verify. */
            tempToken: string;
        };
        /** @description Un user bloqué (retourné par GET /blocks). */
        BlockEntry: {
            /** Format: uuid */
            id: string;
            pseudo: string;
            displayName?: string | null;
            avatarUrl?: string | null;
            /**
             * Format: date-time
             * @description createdAt de la ligne `blocks`.
             */
            since: string;
        };
        /** @description Un jeu supporté par la plateforme. */
        Game: {
            /**
             * @description Slug du jeu (PK).
             * @example cs2
             */
            id: string;
            /** @example Counter-Strike 2 */
            name: string;
            /**
             * @description Provider d'identifiant in-game requis pour s'inscrire à un match de ce jeu.
             * @enum {string}
             */
            requiredProvider: "riot" | "steam" | "epic" | "chess_com";
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Une compétition (jeu × format) avec son ELO indépendant. */
        Ladder: {
            /** Format: uuid */
            id: string;
            /** @example cs2 */
            gameId: string;
            /** @enum {string} */
            format: "1v1" | "2v2" | "3v3" | "5v5";
            /** @example Counter-Strike 2 5v5 */
            name: string;
            /**
             * @description Durée pendant laquelle la team/user est verrouillée après le début d'un match. Aussi le délai minimum avant soumission de score.
             * @example 60
             */
            lockoutMinutes: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Un compte externe (in-game) lié par l'user (§5.1 du design). */
        ExternalAccount: {
            /** @enum {string} */
            provider: "riot" | "steam" | "epic" | "chess_com";
            /**
             * @description Identifiant du compte chez le provider (saisi manuellement au MVP).
             * @example STEAM_76561198000000000
             */
            externalId: string;
            /** @description true si la liaison a été vérifiée (OAuth futur). Au MVP toujours false (liaison manuelle déclarative). */
            verified: boolean;
        };
        /** @description Ligne brute d'une équipe (renvoyée à la création). */
        Team: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ladderId: string;
            name: string;
            /** Format: uuid */
            captainId: string;
            logoUrl: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Une de mes teams (GET /teams), infos ladder aplaties. */
        TeamListItem: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            ladderId: string;
            /** @description Nom du ladder */
            ladder: string;
            /** @enum {string} */
            format: "1v1" | "2v2" | "3v3" | "5v5";
            gameId: string;
            isCaptain: boolean;
            logoUrl: string | null;
        };
        /** @description Détail d'une team (GET /teams/{id}), infos ladder aplaties. */
        TeamDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            ladderId: string;
            ladderName: string;
            /** @enum {string} */
            format: "1v1" | "2v2" | "3v3" | "5v5";
            gameId: string;
            /** Format: uuid */
            captainId: string;
            logoUrl: string | null;
        };
        /** @description Un membre d'une team (le capitaine y figure avec isCaptain=true). */
        TeamMember: {
            /** Format: uuid */
            id: string;
            pseudo: string;
            displayName: string | null;
            avatarUrl: string | null;
            isCaptain: boolean;
        };
    };
    responses: {
        /** @description Token absent, invalide ou expiré */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Erreur interne */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
